// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface GameScreenshots {
    count:    number;
    next:     null;
    previous: null;
    results:  Result[];
}

export interface Result {
    id:         number;
    image:      string;
    width:      number;
    height:     number;
    is_deleted: boolean;
}
